// <auto-generated />
namespace BugManagementSystem.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class initialsetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialsetup));
        
        string IMigrationMetadata.Id
        {
            get { return "201602051100496_initial-setup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
